### ISSUE TITLE
bug in plot.fpaircase when plotting quantiles

### ISSUE THREAD

**Issue by annecori** [reconhub/vimes#8]
when calling plot.fpaircase with a quantile ('y') argument, the quantiles are calculated using the x function without the pi argument specified. 
Example: in the following code, the same vertical line appears for a reporting rate of 90% or 10%; these should be different
```
par(mfrow=c(2, 1))
f_temporal <- fpaircase(type = "temporal", gamma_shape = 2.0, gamma_scale = 1.0)
plot(f_temporal, y = 0.95, pi = 0.9)
plot(f_temporal, y = 0.95, pi = 0.1)
```
I think the issue is in https://github.com/reconhub/vimes/blob/master/R/fpaircase.R#L156 , where `quant <- get_quantiles(x, y)` should be replaced by something like `quant <- get_quantiles(f_x, y)` (although this code doesn't work as f_x is not of class fpaircase so needs to be adapted to reflect that).

**Comment by thibautjombart** [comment]
Fixed at:
eb9da9cff4aa4746fc8b344fadaceb856d78c410
